[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/categories"
  to = "/blog/categories"
  status = 301
  force = false

[[redirects]]
  from = "/tags/blog/"
  to = "/blog/tags"
  status = 301
  force = false